@startuml

title UML-Deployment

skinparam componentStyle uml1

node "<<Smartphone>>" as smartphone {
    node "<<OC Android>>" {
        component [ *.apk(Android Studio)]
    }
}

interface TouchScreen

TouchScreen - smartphone

@enduml