@startuml

title Use Case Diagram
left to right direction
actor Користувач as User
actor Споживач as Consumer
actor ТехнічнаПідтримка as Technical_Support

rectangle Software {

    usecase "Надсилання та отримання повідомлень про психологічно-емоційний стан" as psych_emot_message
    usecase "Отримання повідомлення про освітленість" as lighting_messages
    usecase "Аналіз наданої інформації" as received_data_analyses
    usecase "Надання питань та відповідей " as technical_questions
    usecase "Авторизація" as auth

    received_data_analyses .> lighting_messages : include
    lighting_messages .> psych_emot_message : include

    Consumer -- psych_emot_message
    Consumer -- lighting_messages
    Consumer -- received_data_analyses
    Consumer -- technical_questions

    Technical_Support -- technical_questions

    User -- auth
    User -- Consumer
    User -- Technical_Support
}

@enduml